{
  "artifacts": [], 
  "command": "main", 
  "experiment": {
    "base_dir": "/home/v-chaoqw/MYSFC-ORI", 
    "dependencies": [
      "numpy==1.13.3", 
      "sacred==0.7.2"
    ], 
    "mainfile": "configuration.py", 
    "name": "Siam-FC", 
    "repositories": [], 
    "sources": [
      [
        "configuration.py", 
        "_sources/configuration_e3604cb3d08ac26eb84e21477085cd65.py"
      ]
    ]
  }, 
  "fail_trace": [
    "Traceback (most recent call last):\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/sacred/config/captured_function.py\", line 48, in captured_function\n    result = wrapped(*args, **kwargs)\n", 
    "  File \"train_track_model.py\", line 125, in main\n    response=model.build()\n", 
    "  File \"/home/v-chaoqw/MYSFC-ORI/models/track_model.py\", line 269, in build\n    self.build_image_embeddings()\n", 
    "  File \"/home/v-chaoqw/MYSFC-ORI/models/track_model.py\", line 136, in build_image_embeddings\n    self.examplar_embeds, _ = embedding_fn(self.examplars)\n", 
    "  File \"/home/v-chaoqw/MYSFC-ORI/embeddings/embedding_factory.py\", line 70, in network_fn\n    return func(images, reuse=reuse)\n", 
    "  File \"/home/v-chaoqw/MYSFC-ORI/embeddings/siamese_fc.py\", line 256, in siamese_fc\n    b1 = ConvOffset2D(128, (3, 3), name='b1', trainable=True)(offset1)#deform_conv(b1,offset1,3, 3, 128, 1, 1, biased=False, rate=1, relu=False, padding=\"VALID\",num_deform_group=4, name='b1')#slim.conv2d(b1, 128, [3, 3], 1, scope='b1')\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/keras/engine/topology.py\", line 575, in __call__\n    self.build(input_shapes[0])\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/keras/layers/convolutional.py\", line 134, in build\n    constraint=self.kernel_constraint)\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/keras/legacy/interfaces.py\", line 87, in wrapper\n    return func(*args, **kwargs)\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/keras/engine/topology.py\", line 396, in add_weight\n    weight = K.variable(initializer(shape),\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/keras/initializers.py\", line 79, in __call__\n    dtype=dtype, seed=self.seed)\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py\", line 3521, in random_normal\n    dtype=dtype, seed=seed)\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/ops/random_ops.py\", line 77, in random_normal\n    mul = rnd * stddev_tensor\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py\", line 821, in binary_op_wrapper\n    return func(x, y, name=name)\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py\", line 1044, in _mul_dispatch\n    return gen_math_ops._mul(x, y, name=name)\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py\", line 1434, in _mul\n    result = _op_def_lib.apply_op(\"Mul\", x=x, y=y, name=name)\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py\", line 768, in apply_op\n    op_def=op_def)\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/framework/ops.py\", line 2338, in create_op\n    set_shapes_for_outputs(ret)\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/framework/ops.py\", line 1719, in set_shapes_for_outputs\n    shapes = shape_func(op)\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/framework/ops.py\", line 1669, in call_with_requiring\n    return call_cpp_shape_fn(op, require_shape_fn=True)\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py\", line 610, in call_cpp_shape_fn\n    debug_python_shape_fn, require_shape_fn)\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py\", line 676, in _call_cpp_shape_fn_impl\n    raise ValueError(err.message)\n", 
    "ValueError: Dimensions must be equal, but are 256 and 2 for 'siamese_fc/conv5/def/b1/random_normal/mul' (op: 'Mul') with input shapes: [3,3,72,256], [2].\n"
  ], 
  "heartbeat": "2017-12-06T08:15:56.233891", 
  "host": {
    "ENV": {}, 
    "cpu": "Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz", 
    "gpus": {
      "driver_version": "375.66", 
      "gpus": [
        {
          "model": "Tesla K80", 
          "persistence_mode": false, 
          "total_memory": 11439
        }, 
        {
          "model": "Tesla K80", 
          "persistence_mode": false, 
          "total_memory": 11439
        }
      ]
    }, 
    "hostname": "GCRAZGDL116", 
    "os": [
      "Linux", 
      "Linux-4.4.0-78-generic-x86_64-with-debian-stretch-sid"
    ], 
    "python_version": "2.7.14"
  }, 
  "meta": {
    "command": "main", 
    "options": {
      "--beat_interval": null, 
      "--capture": null, 
      "--comment": null, 
      "--debug": false, 
      "--enforce_clean": false, 
      "--file_storage": null, 
      "--force": false, 
      "--help": false, 
      "--loglevel": null, 
      "--mongo_db": null, 
      "--name": null, 
      "--pdb": false, 
      "--print_config": false, 
      "--priority": null, 
      "--queue": false, 
      "--sql": null, 
      "--tiny_db": null, 
      "--unobserved": false, 
      "COMMAND": null, 
      "UPDATE": [
        "sfc", 
        "workstation"
      ], 
      "help": false, 
      "with": true
    }
  }, 
  "resources": [], 
  "result": null, 
  "start_time": "2017-12-06T08:15:43.595527", 
  "status": "FAILED", 
  "stop_time": "2017-12-06T08:15:56.235964"
}