{
  "artifacts": [], 
  "command": "main", 
  "experiment": {
    "base_dir": "/home/v-chaoqw/MYSFC-ORI", 
    "dependencies": [
      "numpy==1.12.1", 
      "sacred==0.7.2"
    ], 
    "mainfile": "configuration.py", 
    "name": "Siam-FC", 
    "repositories": [], 
    "sources": [
      [
        "configuration.py", 
        "_sources/configuration_03c4dcf5f0716a8c1f3dbd776b394412.py"
      ]
    ]
  }, 
  "fail_trace": [
    "Traceback (most recent call last):\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/sacred/config/captured_function.py\", line 48, in captured_function\n    result = wrapped(*args, **kwargs)\n", 
    "  File \"train_track_model.py\", line 196, in main\n    sess.run(tf.global_variables_initializer())\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/client/session.py\", line 767, in run\n    run_metadata_ptr)\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/client/session.py\", line 965, in _run\n    feed_dict_string, options, run_metadata)\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/client/session.py\", line 1015, in _do_run\n    target_list, options, run_metadata)\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/client/session.py\", line 1035, in _do_call\n    raise type(e)(node_def, op, message)\n", 
    "InvalidArgumentError: No OpKernel was registered to support Op 'DeformConvBackpropOp' with these attrs.  Registered devices: [CPU], Registered kernels:\n  device='GPU'; T in [DT_DOUBLE]\n  device='GPU'; T in [DT_FLOAT]\n\n\t [[Node: OptimizeLoss/gradients/siamese_fc_1/conv5/def/b1/DeformConvOp_grad/DeformConvBackpropOp = DeformConvBackpropOp[T=DT_FLOAT, data_format=\"NCHW\", deformable_group=4, num_groups=1, padding=\"VALID\", rates=[1, 1, 1, 1], strides=[1, 1, 1, 1]](siamese_fc_1/conv5/def/transpose, siamese_fc/conv5/def/b1/weights/read, siamese_fc_1/conv5/def/transpose_1, OptimizeLoss/gradients/siamese_fc_1/conv5/def/b1/transpose_grad/transpose)]]\n\nCaused by op u'OptimizeLoss/gradients/siamese_fc_1/conv5/def/b1/DeformConvOp_grad/DeformConvBackpropOp', defined at:\n  File \"train_track_model.py\", line 282, in <module>\n    ex.run_commandline()\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/sacred/experiment.py\", line 250, in run_commandline\n    return self.run(cmd_name, config_updates, named_configs, {}, args)\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/sacred/experiment.py\", line 199, in run\n    run()\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/sacred/run.py\", line 229, in __call__\n    self.result = self.main_function(*args)\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/sacred/config/captured_function.py\", line 48, in captured_function\n    result = wrapped(*args, **kwargs)\n  File \"train_track_model.py\", line 144, in main\n    summaries=['learning_rate', 'loss'])\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/optimizers.py\", line 226, in optimize_loss\n    colocate_gradients_with_ops=colocate_gradients_with_ops)\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py\", line 354, in compute_gradients\n    colocate_gradients_with_ops=colocate_gradients_with_ops)\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py\", line 482, in gradients\n    in_grads = grad_fn(op, *out_grads)\n  File \"/home/v-chaoqw/MYSFC-ORI/embeddings/libs/deform_conv_op.py\", line 35, in _deform_conv_grad\n    data_grad = deform_conv_grad_op(data, filter, offset, grad, strides, rates, num_groups, deformable_group, padding, data_format)\n  File \"<string>\", line 87, in deform_conv_backprop_op\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py\", line 763, in apply_op\n    op_def=op_def)\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/framework/ops.py\", line 2395, in create_op\n    original_op=self._default_original_op, op_def=op_def)\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/framework/ops.py\", line 1264, in __init__\n    self._traceback = _extract_stack()\n\n...which was originally created as op u'siamese_fc_1/conv5/def/b1/DeformConvOp', defined at:\n  File \"train_track_model.py\", line 282, in <module>\n    ex.run_commandline()\n[elided 3 identical lines from previous traceback]\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/sacred/config/captured_function.py\", line 48, in captured_function\n    result = wrapped(*args, **kwargs)\n  File \"train_track_model.py\", line 125, in main\n    response=model.build()\n  File \"/home/v-chaoqw/MYSFC-ORI/models/track_model.py\", line 269, in build\n    self.build_image_embeddings()\n  File \"/home/v-chaoqw/MYSFC-ORI/models/track_model.py\", line 137, in build_image_embeddings\n    self.instance_embeds, _ = embedding_fn(self.instances, reuse=True)\n  File \"/home/v-chaoqw/MYSFC-ORI/embeddings/embedding_factory.py\", line 70, in network_fn\n    return func(images, reuse=reuse)\n  File \"/home/v-chaoqw/MYSFC-ORI/embeddings/siamese_fc.py\", line 230, in siamese_fc\n    b1 = deform_conv(b1,offset1,3, 3, 128, 1, 1, biased=False, rate=1, relu=False, padding=\"VALID\",num_deform_group=4, name='b1')#slim.conv2d(b1, 128, [3, 3], 1, scope='b1')\n  File \"/home/v-chaoqw/MYSFC-ORI/embeddings/siamese_fc.py\", line 152, in deform_conv\n    dconv = trans2NHWC(dconvolve(data, kernel, offset))\n  File \"/home/v-chaoqw/MYSFC-ORI/embeddings/siamese_fc.py\", line 144, in <lambda>\n    dconvolve = lambda i, k, o: deform_conv_op.deform_conv_op(i, k, o, strides = [1, 1, s_h, s_w], rates=[1, 1, rate, rate], padding=padding, num_groups=num_groups, deformable_group=num_deform_group)\n  File \"<string>\", line 45, in deform_conv_op\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py\", line 763, in apply_op\n    op_def=op_def)\n\nInvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'DeformConvBackpropOp' with these attrs.  Registered devices: [CPU], Registered kernels:\n  device='GPU'; T in [DT_DOUBLE]\n  device='GPU'; T in [DT_FLOAT]\n\n\t [[Node: OptimizeLoss/gradients/siamese_fc_1/conv5/def/b1/DeformConvOp_grad/DeformConvBackpropOp = DeformConvBackpropOp[T=DT_FLOAT, data_format=\"NCHW\", deformable_group=4, num_groups=1, padding=\"VALID\", rates=[1, 1, 1, 1], strides=[1, 1, 1, 1]](siamese_fc_1/conv5/def/transpose, siamese_fc/conv5/def/b1/weights/read, siamese_fc_1/conv5/def/transpose_1, OptimizeLoss/gradients/siamese_fc_1/conv5/def/b1/transpose_grad/transpose)]]\n\n"
  ], 
  "heartbeat": "2017-12-06T12:32:43.234219", 
  "host": {
    "ENV": {}, 
    "cpu": "Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz", 
    "hostname": "GCRAZGDL116", 
    "os": [
      "Linux", 
      "Linux-4.4.0-101-generic-x86_64-with-debian-stretch-sid"
    ], 
    "python_version": "2.7.14"
  }, 
  "meta": {
    "command": "main", 
    "options": {
      "--beat_interval": null, 
      "--capture": null, 
      "--comment": null, 
      "--debug": false, 
      "--enforce_clean": false, 
      "--file_storage": null, 
      "--force": false, 
      "--help": false, 
      "--loglevel": null, 
      "--mongo_db": null, 
      "--name": null, 
      "--pdb": false, 
      "--print_config": false, 
      "--priority": null, 
      "--queue": false, 
      "--sql": null, 
      "--tiny_db": null, 
      "--unobserved": false, 
      "COMMAND": null, 
      "UPDATE": [
        "sfc", 
        "workstation"
      ], 
      "help": false, 
      "with": true
    }
  }, 
  "resources": [], 
  "result": null, 
  "start_time": "2017-12-06T12:32:33.355004", 
  "status": "FAILED", 
  "stop_time": "2017-12-06T12:32:43.235302"
}