{
  "artifacts": [], 
  "command": "main", 
  "experiment": {
    "base_dir": "/home/v-chaoqw/MYSFC-ORI", 
    "dependencies": [
      "numpy==1.13.3", 
      "sacred==0.7.2"
    ], 
    "mainfile": "configuration.py", 
    "name": "Obj-Siam-FC", 
    "repositories": [], 
    "sources": [
      [
        "configuration.py", 
        "_sources/configuration_fbded3c3ecf43cb13b70ceaa4f102f94.py"
      ]
    ]
  }, 
  "fail_trace": [
    "Traceback (most recent call last):\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/sacred/config/captured_function.py\", line 48, in captured_function\n    result = wrapped(*args, **kwargs)\n", 
    "  File \"train_track_model.py\", line 205, in main\n    _, loss, batch_loss = sess.run([train_op, model.total_loss, model.batch_loss])\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/client/session.py\", line 778, in run\n    run_metadata_ptr)\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/client/session.py\", line 982, in _run\n    feed_dict_string, options, run_metadata)\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/client/session.py\", line 1032, in _do_run\n    target_list, options, run_metadata)\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/client/session.py\", line 1052, in _do_call\n    raise type(e)(node_def, op, message)\n", 
    "InvalidArgumentError: Conv2DSlowBackpropInput: Size of out_backprop doesn't match computed: actual = 15, computed = 13\n\t [[Node: OptimizeLoss/gradients/detection/map/while/translation_match_grad/Conv2DBackpropInput = Conv2DBackpropInput[T=DT_FLOAT, data_format=\"NHWC\", padding=\"VALID\", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device=\"/job:localhost/replica:0/task:0/gpu:0\"](OptimizeLoss/gradients/detection/map/while/translation_match_grad/Shape, OptimizeLoss/gradients/detection/map/while/translation_match_grad/Conv2DBackpropInput/StackPop, OptimizeLoss/gradients/detection/map/while/TensorArrayWrite/TensorArrayWriteV3_grad/tuple/control_dependency)]]\n\nCaused by op u'OptimizeLoss/gradients/detection/map/while/translation_match_grad/Conv2DBackpropInput', defined at:\n  File \"train_track_model.py\", line 227, in <module>\n    ex.run_commandline()\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/sacred/experiment.py\", line 250, in run_commandline\n    return self.run(cmd_name, config_updates, named_configs, {}, args)\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/sacred/experiment.py\", line 199, in run\n    run()\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/sacred/run.py\", line 229, in __call__\n    self.result = self.main_function(*args)\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/sacred/config/captured_function.py\", line 48, in captured_function\n    result = wrapped(*args, **kwargs)\n  File \"train_track_model.py\", line 144, in main\n    summaries=['learning_rate', 'loss'])\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/optimizers.py\", line 237, in optimize_loss\n    colocate_gradients_with_ops=colocate_gradients_with_ops)\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py\", line 386, in compute_gradients\n    colocate_gradients_with_ops=colocate_gradients_with_ops)\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py\", line 560, in gradients\n    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py\", line 368, in _MaybeCompile\n    return grad_fn()  # Exit early\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py\", line 560, in <lambda>\n    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/ops/nn_grad.py\", line 368, in _Conv2DGrad\n    op.get_attr(\"data_format\")),\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py\", line 496, in conv2d_backprop_input\n    data_format=data_format, name=name)\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py\", line 768, in apply_op\n    op_def=op_def)\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/framework/ops.py\", line 2336, in create_op\n    original_op=self._default_original_op, op_def=op_def)\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/framework/ops.py\", line 1228, in __init__\n    self._traceback = _extract_stack()\n\n...which was originally created as op u'detection/map/while/translation_match', defined at:\n  File \"train_track_model.py\", line 227, in <module>\n    ex.run_commandline()\n[elided 3 identical lines from previous traceback]\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/sacred/config/captured_function.py\", line 48, in captured_function\n    result = wrapped(*args, **kwargs)\n  File \"train_track_model.py\", line 125, in main\n    model.build()\n  File \"/home/v-chaoqw/MYSFC-ORI/models/track_model.py\", line 270, in build\n    self.build_detection()\n  File \"/home/v-chaoqw/MYSFC-ORI/models/track_model.py\", line 157, in build_detection\n    (self.instance_embeds, self.templates), dtype=self.instance_embeds.dtype)  # of shape [16, 1, 17, 17, 1]\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/ops/functional_ops.py\", line 389, in map_fn\n    swap_memory=swap_memory)\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py\", line 2623, in while_loop\n    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py\", line 2456, in BuildLoop\n    pred, body, original_loop_vars, loop_vars, shape_invariants)\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py\", line 2406, in _BuildLoop\n    body_result = body(*packed_vars_for_body)\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/ops/functional_ops.py\", line 379, in compute\n    packed_fn_values = fn(packed_values)\n  File \"/home/v-chaoqw/MYSFC-ORI/models/track_model.py\", line 156, in <lambda>\n    lambda x: _translation_match(x[0], x[1]),\n  File \"/home/v-chaoqw/MYSFC-ORI/models/track_model.py\", line 153, in _translation_match\n    return tf.nn.conv2d(x, z, strides=[1, 1, 1, 1], padding='VALID', name='translation_match')\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py\", line 403, in conv2d\n    data_format=data_format, name=name)\n\nInvalidArgumentError (see above for traceback): Conv2DSlowBackpropInput: Size of out_backprop doesn't match computed: actual = 15, computed = 13\n\t [[Node: OptimizeLoss/gradients/detection/map/while/translation_match_grad/Conv2DBackpropInput = Conv2DBackpropInput[T=DT_FLOAT, data_format=\"NHWC\", padding=\"VALID\", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device=\"/job:localhost/replica:0/task:0/gpu:0\"](OptimizeLoss/gradients/detection/map/while/translation_match_grad/Shape, OptimizeLoss/gradients/detection/map/while/translation_match_grad/Conv2DBackpropInput/StackPop, OptimizeLoss/gradients/detection/map/while/TensorArrayWrite/TensorArrayWriteV3_grad/tuple/control_dependency)]]\n\n"
  ], 
  "heartbeat": "2017-12-02T11:30:27.142098", 
  "host": {
    "ENV": {}, 
    "cpu": "Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz", 
    "gpus": {
      "driver_version": "375.66", 
      "gpus": [
        {
          "model": "Tesla K80", 
          "persistence_mode": false, 
          "total_memory": 11439
        }, 
        {
          "model": "Tesla K80", 
          "persistence_mode": false, 
          "total_memory": 11439
        }
      ]
    }, 
    "hostname": "GCRAZGDL116", 
    "os": [
      "Linux", 
      "Linux-4.4.0-78-generic-x86_64-with-debian-stretch-sid"
    ], 
    "python_version": "2.7.14"
  }, 
  "meta": {
    "command": "main", 
    "options": {
      "--beat_interval": null, 
      "--capture": null, 
      "--comment": null, 
      "--debug": false, 
      "--enforce_clean": false, 
      "--file_storage": null, 
      "--force": false, 
      "--help": false, 
      "--loglevel": null, 
      "--mongo_db": null, 
      "--name": null, 
      "--pdb": false, 
      "--print_config": false, 
      "--priority": null, 
      "--queue": false, 
      "--sql": null, 
      "--tiny_db": null, 
      "--unobserved": false, 
      "COMMAND": null, 
      "UPDATE": [
        "sfc", 
        "workstation"
      ], 
      "help": false, 
      "with": true
    }
  }, 
  "resources": [], 
  "result": null, 
  "start_time": "2017-12-02T11:30:14.808996", 
  "status": "FAILED", 
  "stop_time": "2017-12-02T11:30:27.143533"
}