{
  "artifacts": [], 
  "command": "main", 
  "experiment": {
    "base_dir": "/home/v-chaoqw/MYSFC-ORI", 
    "dependencies": [
      "numpy==1.13.3", 
      "sacred==0.7.2"
    ], 
    "mainfile": "configuration.py", 
    "name": "Obj-Siam-FC", 
    "repositories": [], 
    "sources": [
      [
        "configuration.py", 
        "_sources/configuration_8d5f2e804e4abe566d9bb78958174fe4.py"
      ]
    ]
  }, 
  "fail_trace": [
    "Traceback (most recent call last):\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/sacred/config/captured_function.py\", line 48, in captured_function\n    result = wrapped(*args, **kwargs)\n", 
    "  File \"train_track_model.py\", line 125, in main\n    model.build()\n", 
    "  File \"/home/v-chaoqw/MYSFC-ORI/models/track_model.py\", line 267, in build\n    self.build_inputs()\n", 
    "  File \"/home/v-chaoqw/MYSFC-ORI/models/track_model.py\", line 73, in build_inputs\n    self.dataloader = DataLoader(self.config['prefetch_config'], self.is_training())\n", 
    "  File \"/home/v-chaoqw/MYSFC-ORI/datasets/dataloader.py\", line 72, in __init__\n    self.dataset = VID(root, config['input_imdb'], config['time_steps'], config['max_frame_dist'], transform)\n", 
    "  File \"/home/v-chaoqw/MYSFC-ORI/datasets/vid.py\", line 57, in __init__\n    with open(imdb_path, 'rb') as f:\n", 
    "IOError: [Errno 2] No such file or directory: u'/home/v-chaoqw/MYSFC-ORI/workspace/pickle/train_imdb.pickle'\n"
  ], 
  "heartbeat": "2017-11-30T07:14:07.199544", 
  "host": {
    "ENV": {}, 
    "cpu": "Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz", 
    "gpus": {
      "driver_version": "375.66", 
      "gpus": [
        {
          "model": "Tesla K80", 
          "persistence_mode": false, 
          "total_memory": 11439
        }, 
        {
          "model": "Tesla K80", 
          "persistence_mode": false, 
          "total_memory": 11439
        }
      ]
    }, 
    "hostname": "GCRAZGDL116", 
    "os": [
      "Linux", 
      "Linux-4.4.0-78-generic-x86_64-with-debian-stretch-sid"
    ], 
    "python_version": "2.7.14"
  }, 
  "meta": {
    "command": "main", 
    "options": {
      "--beat_interval": null, 
      "--capture": null, 
      "--comment": null, 
      "--debug": false, 
      "--enforce_clean": false, 
      "--file_storage": null, 
      "--force": false, 
      "--help": false, 
      "--loglevel": null, 
      "--mongo_db": null, 
      "--name": null, 
      "--pdb": false, 
      "--print_config": false, 
      "--priority": null, 
      "--queue": false, 
      "--sql": null, 
      "--tiny_db": null, 
      "--unobserved": false, 
      "COMMAND": null, 
      "UPDATE": [
        "sfc", 
        "workstation"
      ], 
      "help": false, 
      "with": true
    }
  }, 
  "resources": [], 
  "result": null, 
  "start_time": "2017-11-30T07:14:07.194212", 
  "status": "FAILED", 
  "stop_time": "2017-11-30T07:14:07.200595"
}