{
  "artifacts": [], 
  "command": "main", 
  "experiment": {
    "base_dir": "/home/v-chaoqw/MYSFC-ORI", 
    "dependencies": [
      "numpy==1.12.1", 
      "sacred==0.7.2"
    ], 
    "mainfile": "configuration.py", 
    "name": "Siam-FC", 
    "repositories": [], 
    "sources": [
      [
        "configuration.py", 
        "_sources/configuration_02775d277e547f021248eed78a64d457.py"
      ]
    ]
  }, 
  "fail_trace": [
    "Traceback (most recent call last):\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/sacred/config/captured_function.py\", line 48, in captured_function\n    result = wrapped(*args, **kwargs)\n", 
    "  File \"train_track_model.py\", line 272, in main\n    summary_str = sess.run(summary_op)\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/client/session.py\", line 778, in run\n    run_metadata_ptr)\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/client/session.py\", line 982, in _run\n    feed_dict_string, options, run_metadata)\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/client/session.py\", line 1032, in _do_run\n    target_list, options, run_metadata)\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/client/session.py\", line 1052, in _do_call\n    raise type(e)(node_def, op, message)\n", 
    "InvalidArgumentError: Nan in summary histogram for: Monitor_summary/offset1_inst\n\t [[Node: Monitor_summary/offset1_inst = HistogramSummary[T=DT_FLOAT, _device=\"/job:localhost/replica:0/task:0/cpu:0\"](Monitor_summary/offset1_inst/tag, siamese_fc_1/conv5/def/offset1/BiasAdd/_89)]]\n\t [[Node: Monitor_summary/CD-err/FloorMod/_71 = _Recv[client_terminated=false, recv_device=\"/job:localhost/replica:0/task:0/gpu:0\", send_device=\"/job:localhost/replica:0/task:0/cpu:0\", send_device_incarnation=1, tensor_name=\"edge_749_Monitor_summary/CD-err/FloorMod\", tensor_type=DT_INT64, _device=\"/job:localhost/replica:0/task:0/gpu:0\"]()]]\n\nCaused by op u'Monitor_summary/offset1_inst', defined at:\n  File \"train_track_model.py\", line 286, in <module>\n    ex.run_commandline()\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/sacred/experiment.py\", line 250, in run_commandline\n    return self.run(cmd_name, config_updates, named_configs, {}, args)\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/sacred/experiment.py\", line 199, in run\n    run()\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/sacred/run.py\", line 229, in __call__\n    self.result = self.main_function(*args)\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/sacred/config/captured_function.py\", line 48, in captured_function\n    result = wrapped(*args, **kwargs)\n  File \"train_track_model.py\", line 127, in main\n    response=model.build()\n  File \"/home/v-chaoqw/MYSFC-ORI/models/track_model.py\", line 275, in build\n    self.build_loss()\n  File \"/home/v-chaoqw/MYSFC-ORI/models/track_model.py\", line 234, in build_loss\n    tf.summary.histogram('offset1_inst', self.offset1_inst)\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/summary/summary.py\", line 209, in histogram\n    tag=scope.rstrip('/'), values=values, name=scope)\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/ops/gen_logging_ops.py\", line 139, in _histogram_summary\n    name=name)\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py\", line 768, in apply_op\n    op_def=op_def)\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/framework/ops.py\", line 2336, in create_op\n    original_op=self._default_original_op, op_def=op_def)\n  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/framework/ops.py\", line 1228, in __init__\n    self._traceback = _extract_stack()\n\nInvalidArgumentError (see above for traceback): Nan in summary histogram for: Monitor_summary/offset1_inst\n\t [[Node: Monitor_summary/offset1_inst = HistogramSummary[T=DT_FLOAT, _device=\"/job:localhost/replica:0/task:0/cpu:0\"](Monitor_summary/offset1_inst/tag, siamese_fc_1/conv5/def/offset1/BiasAdd/_89)]]\n\t [[Node: Monitor_summary/CD-err/FloorMod/_71 = _Recv[client_terminated=false, recv_device=\"/job:localhost/replica:0/task:0/gpu:0\", send_device=\"/job:localhost/replica:0/task:0/cpu:0\", send_device_incarnation=1, tensor_name=\"edge_749_Monitor_summary/CD-err/FloorMod\", tensor_type=DT_INT64, _device=\"/job:localhost/replica:0/task:0/gpu:0\"]()]]\n\n"
  ], 
  "heartbeat": "2017-12-08T10:20:45.839519", 
  "host": {
    "ENV": {}, 
    "cpu": "Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz", 
    "gpus": {
      "driver_version": "384.81", 
      "gpus": [
        {
          "model": "Tesla K80", 
          "persistence_mode": false, 
          "total_memory": 11439
        }, 
        {
          "model": "Tesla K80", 
          "persistence_mode": false, 
          "total_memory": 11439
        }
      ]
    }, 
    "hostname": "GCRAZGDL116", 
    "os": [
      "Linux", 
      "Linux-4.4.0-101-generic-x86_64-with-debian-stretch-sid"
    ], 
    "python_version": "2.7.14"
  }, 
  "meta": {
    "command": "main", 
    "options": {
      "--beat_interval": null, 
      "--capture": null, 
      "--comment": null, 
      "--debug": false, 
      "--enforce_clean": false, 
      "--file_storage": null, 
      "--force": false, 
      "--help": false, 
      "--loglevel": null, 
      "--mongo_db": null, 
      "--name": null, 
      "--pdb": false, 
      "--print_config": false, 
      "--priority": null, 
      "--queue": false, 
      "--sql": null, 
      "--tiny_db": null, 
      "--unobserved": false, 
      "COMMAND": null, 
      "UPDATE": [
        "sfc", 
        "workstation"
      ], 
      "help": false, 
      "with": true
    }
  }, 
  "resources": [], 
  "result": null, 
  "start_time": "2017-12-08T10:19:41.550587", 
  "status": "FAILED", 
  "stop_time": "2017-12-08T10:20:45.840809"
}